name: branch

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates sqlite

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build-deps deps test deploy

  e2e:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - build
    continue-on-error: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build and push ephemeral Docker image
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/tracker
          registry: https://docker.pkg.github.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          tag_with_ref: true
          dockerfile: Dockerfile.dev
          push: true
