name: branch

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: golang:1.14-alpine3.11
    steps:
      - name: Prepare
        run: apk -U upgrade && apk add build-base git ca-certificates sqlite

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make build-deps deps test deploy

  e2e:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs:
      - build
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest

      - name: Authenticate to GitHub Packages
        run: docker login https://docker.pkg.github.com -u ${REPO_OWNER} -p $GITHUB_TOKEN
        env:
          REPO_OWNER: ${{ github.repository_owner }}
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Build Container Image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --build-arg VERSION=${GITHUB_REF##*/v} \
            --tag docker.pkg.github.com/${REPOSITORY}/tracker:${PR_NUMBER} \
            -f Dockerfile \
            . \
            --push
        env:
          REPOSITORY: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.number }}
